on:
  push:
    branches:
      - "develop"
      - "master"

jobs:  
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Create semver tag"
        id: semver-tag
        uses: gandarez/semver-action@v1.3.2
        with:
          prerelease_id: "alpha"
          user_email: "<>"
          username: "WakaTime Actions"
          debug: "true"
