on:
  push:
    branches:
      - "develop"
      - "master"

jobs:  
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: "Create semver tag"
        id: semver-tag
        uses: gandarez/semver-action@v1.4.0-rc.1
        with:
          prerelease_id: "alpha"
          debug: "true"
