name: "Create Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "Get the version"
        id: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: "Slack notification"
        uses: 8398a7/action-slack@v3
        if: ${{ success() }}
        with:
          status: custom
          fields: message
          custom_payload: |
            {
              username: 'WakaTime Bot',
              icon_emoji: ':mega:',
              attachments: [{
                color: 'good',
                pretext: 'New version has been released for <https://github.com/wakatime/wakatime-cli|wakatime-cli>',
                title: `${{ steps.version.outputs.version }}`,
                title_link: `https://github.com/gandarez/git-history/releases/tag/${{ steps.version.outputs.version }}`,
                text: `${process.env.AS_MESSAGE}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
